### ISSUE TITLE
Consider spinning out the Ble / wearable functionality

### ISSUE THREAD

**Issue by genecyber** [xamarin/Monkey.Robotics#25]
I almost missed it!

I'm looking for bluetooth and wearable capabilities and Id missed this package twice before I decided to take a closer look at bluetooth. This specific functionality is valuable by itself and I know others will skip by something that appears only for robotics.

**Comment by MichaelRoop** [comment]
Hi Shannon,

 

I also had been looking for Bluetooth LE.  However, once I started experimenting with the Monkey Robotics Bluetooth I discovered that the LE Guids are hardcoded for Red Bear Labs (I think) module.  I believe that would be a popular NetDuino Bluetooth Shield.  The guids are to setup the characteristic for sending and receiving messages.  

 

I made some modifications on a branch so that you could initialize the Bluetooth with a Guid set of your choice.  I issued a pull request but have not heard if it has been looked at.

 

I also created my own reader writer to replace their stream derived object LEStream object.  Most of the Stream interface was left with not implemented exceptions.  Did not seem to fit very well

 

Once the modifications are in place we have been successful in doing some prototype connections, and send and receives against Blue Radio module

 

Michael

**Comment by conceptdev** [comment]
Thanks for your feedback. As wearables and IoT becomes more important, maybe we do need to reconsider naming (or at least explain this library better).

@MichaelRoop will check your PR and see if we can bring it in. The idea looks sound, just need to find some time to test!

**Comment by MichaelRoop** [comment]
Just to reiterate.  Because of my setup I was only able to test on IOS and Android.

 

Regards,

 

Michael Roop
